export function Adsr() {
  return (
    <>
      <svg className="defs">
        <defs>
          <radialGradient id="grad-dial-soft-shadow" cx="0.5" cy="0.5" r="0.5">
            <stop offset="85%" stopColor="#242a2e" stopOpacity="0.4"></stop>
            <stop offset="100%" stopColor="#242a2e" stopOpacity="0"></stop>
          </radialGradient>
          <linearGradient id="grad-dial-base" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="#52595f"></stop>
            <stop offset="100%" stopColor="#2b3238"></stop>
          </linearGradient>
          <linearGradient id="grad-dial-highlight" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="#70777d" stopOpacity="1"></stop>
            <stop offset="40%" stopColor="#70777d" stopOpacity="0"></stop>
            <stop offset="55%" stopColor="#70777d" stopOpacity="0"></stop>
            <stop offset="100%" stopColor="#70777d" stopOpacity="0.3"></stop>
          </linearGradient>
          <filter id="glow">
            <feGaussianBlur
              in="SourceGraphic"
              result="blur"
              stdDeviation="2"
            ></feGaussianBlur>
            <feComposite
              in="blur"
              in2="SourceGraphic"
              operator="over"
            ></feComposite>
          </filter>
        </defs>
      </svg>
      <div className="fl-studio-envelope">
        <div className="fl-studio-envelope__visualizer">
          <svg
            className="envelope-visualizer"
            viewBox="0 0 300 100"
            preserveAspectRatio="xMinYMid slice"
          >
            <path
              className="envelope-shape"
              d="M0,100L0,0"
              fill="transparent"
              stroke="#4eccff"
              strokeWidth="2"
            ></path>
            <circle
              className="delay"
              cx="0"
              cy="100"
              r="6"
              fill="#284554"
              stroke="#4eccff"
              strokeWidth="2"
            ></circle>
            <circle
              className="attack"
              cx="0"
              cy="0"
              r="6"
              fill="#284554"
              stroke="#4eccff"
              strokeWidth="2"
            ></circle>
            <circle
              className="hold"
              cx="0"
              cy="0"
              r="6"
              fill="#284554"
              stroke="#4eccff"
              strokeWidth="2"
            ></circle>
            <circle
              className="decay"
              cx="0"
              cy="100"
              r="6"
              fill="#284554"
              stroke="#4eccff"
              strokeWidth="2"
            ></circle>
            <circle
              className="release"
              cx="0"
              cy="100"
              r="6"
              fill="#284554"
              stroke="#4eccff"
              strokeWidth="2"
            ></circle>
          </svg>
        </div>
        <div className="fl-studio-envelope__controls">
          <div className="fl-studio-envelope__control">
            <div className="knob-input fl-studio-envelope__knob envelope-knob delay">
              <svg className="knob-input__visual" viewBox="0 0 40 40">
                <circle
                  className="focus-indicator"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#4eccff"
                  filter="url(#glow)"
                ></circle>
                <circle
                  className="indicator-ring-bg"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#353b3f"
                  stroke="#23292d"
                ></circle>
                <path
                  className="indicator-ring"
                  d="M20,20Z"
                  fill="#4eccff"
                ></path>
                <g className="dial">
                  <circle
                    cx="20"
                    cy="20"
                    r="16"
                    fill="url(#grad-dial-soft-shadow)"
                  ></circle>
                  <ellipse
                    cx="20"
                    cy="22"
                    rx="14"
                    ry="14.5"
                    fill="#242a2e"
                    opacity="0.15"
                  ></ellipse>
                  <circle
                    cx="20"
                    cy="20"
                    r="14"
                    fill="url(#grad-dial-base)"
                    stroke="#242a2e"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    cx="20"
                    cy="20"
                    r="13"
                    fill="transparent"
                    stroke="url(#grad-dial-highlight)"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    className="dial-highlight"
                    cx="20"
                    cy="20"
                    r="14"
                    fill="#fff"
                  ></circle>
                  <circle
                    className="indicator-dot"
                    cx="20"
                    cy="30"
                    r="1.5"
                    fill="#4eccff"
                  ></circle>
                </g>
              </svg>
            </div>
            <div className="fl-studio-envelope__label">delay</div>
          </div>
          <div className="fl-studio-envelope__control">
            <div className="knob-input fl-studio-envelope__knob envelope-knob attack">
              <svg className="knob-input__visual" viewBox="0 0 40 40">
                <circle
                  className="focus-indicator"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#4eccff"
                  filter="url(#glow)"
                ></circle>
                <circle
                  className="indicator-ring-bg"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#353b3f"
                  stroke="#23292d"
                ></circle>
                <path
                  className="indicator-ring"
                  d="M20,20Z"
                  fill="#4eccff"
                ></path>
                <g className="dial">
                  <circle
                    cx="20"
                    cy="20"
                    r="16"
                    fill="url(#grad-dial-soft-shadow)"
                  ></circle>
                  <ellipse
                    cx="20"
                    cy="22"
                    rx="14"
                    ry="14.5"
                    fill="#242a2e"
                    opacity="0.15"
                  ></ellipse>
                  <circle
                    cx="20"
                    cy="20"
                    r="14"
                    fill="url(#grad-dial-base)"
                    stroke="#242a2e"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    cx="20"
                    cy="20"
                    r="13"
                    fill="transparent"
                    stroke="url(#grad-dial-highlight)"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    className="dial-highlight"
                    cx="20"
                    cy="20"
                    r="14"
                    fill="#fff"
                  ></circle>
                  <circle
                    className="indicator-dot"
                    cx="20"
                    cy="30"
                    r="1.5"
                    fill="#4eccff"
                  ></circle>
                </g>
              </svg>
            </div>
            <div className="fl-studio-envelope__label">att</div>
          </div>
          <div className="fl-studio-envelope__control">
            <div className="knob-input fl-studio-envelope__knob envelope-knob hold">
              <svg className="knob-input__visual" viewBox="0 0 40 40">
                <circle
                  className="focus-indicator"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#4eccff"
                  filter="url(#glow)"
                ></circle>
                <circle
                  className="indicator-ring-bg"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#353b3f"
                  stroke="#23292d"
                ></circle>
                <path
                  className="indicator-ring"
                  d="M20,20Z"
                  fill="#4eccff"
                ></path>
                <g className="dial">
                  <circle
                    cx="20"
                    cy="20"
                    r="16"
                    fill="url(#grad-dial-soft-shadow)"
                  ></circle>
                  <ellipse
                    cx="20"
                    cy="22"
                    rx="14"
                    ry="14.5"
                    fill="#242a2e"
                    opacity="0.15"
                  ></ellipse>
                  <circle
                    cx="20"
                    cy="20"
                    r="14"
                    fill="url(#grad-dial-base)"
                    stroke="#242a2e"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    cx="20"
                    cy="20"
                    r="13"
                    fill="transparent"
                    stroke="url(#grad-dial-highlight)"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    className="dial-highlight"
                    cx="20"
                    cy="20"
                    r="14"
                    fill="#fff"
                  ></circle>
                  <circle
                    className="indicator-dot"
                    cx="20"
                    cy="30"
                    r="1.5"
                    fill="#4eccff"
                  ></circle>
                </g>
              </svg>
            </div>
            <div className="fl-studio-envelope__label">hold</div>
          </div>
          <div className="fl-studio-envelope__control">
            <div className="knob-input fl-studio-envelope__knob envelope-knob decay">
              <svg className="knob-input__visual" viewBox="0 0 40 40">
                <circle
                  className="focus-indicator"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#4eccff"
                  filter="url(#glow)"
                ></circle>
                <circle
                  className="indicator-ring-bg"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#353b3f"
                  stroke="#23292d"
                ></circle>
                <path
                  className="indicator-ring"
                  d="M20,20Z"
                  fill="#4eccff"
                ></path>
                <g className="dial">
                  <circle
                    cx="20"
                    cy="20"
                    r="16"
                    fill="url(#grad-dial-soft-shadow)"
                  ></circle>
                  <ellipse
                    cx="20"
                    cy="22"
                    rx="14"
                    ry="14.5"
                    fill="#242a2e"
                    opacity="0.15"
                  ></ellipse>
                  <circle
                    cx="20"
                    cy="20"
                    r="14"
                    fill="url(#grad-dial-base)"
                    stroke="#242a2e"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    cx="20"
                    cy="20"
                    r="13"
                    fill="transparent"
                    stroke="url(#grad-dial-highlight)"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    className="dial-highlight"
                    cx="20"
                    cy="20"
                    r="14"
                    fill="#fff"
                  ></circle>
                  <circle
                    className="indicator-dot"
                    cx="20"
                    cy="30"
                    r="1.5"
                    fill="#4eccff"
                  ></circle>
                </g>
              </svg>
            </div>
            <div className="fl-studio-envelope__label">dec</div>
          </div>
          <div className="fl-studio-envelope__control">
            <div className="knob-input fl-studio-envelope__knob envelope-knob sustain">
              <svg className="knob-input__visual" viewBox="0 0 40 40">
                <circle
                  className="focus-indicator"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#4eccff"
                  filter="url(#glow)"
                ></circle>
                <circle
                  className="indicator-ring-bg"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#353b3f"
                  stroke="#23292d"
                ></circle>
                <path
                  className="indicator-ring"
                  d="M20,20Z"
                  fill="#4eccff"
                ></path>
                <g className="dial">
                  <circle
                    cx="20"
                    cy="20"
                    r="16"
                    fill="url(#grad-dial-soft-shadow)"
                  ></circle>
                  <ellipse
                    cx="20"
                    cy="22"
                    rx="14"
                    ry="14.5"
                    fill="#242a2e"
                    opacity="0.15"
                  ></ellipse>
                  <circle
                    cx="20"
                    cy="20"
                    r="14"
                    fill="url(#grad-dial-base)"
                    stroke="#242a2e"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    cx="20"
                    cy="20"
                    r="13"
                    fill="transparent"
                    stroke="url(#grad-dial-highlight)"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    className="dial-highlight"
                    cx="20"
                    cy="20"
                    r="14"
                    fill="#fff"
                  ></circle>
                  <circle
                    className="indicator-dot"
                    cx="20"
                    cy="30"
                    r="1.5"
                    fill="#4eccff"
                  ></circle>
                </g>
              </svg>
            </div>
            <div className="fl-studio-envelope__label">sus</div>
          </div>
          <div className="fl-studio-envelope__control">
            <div className="knob-input fl-studio-envelope__knob envelope-knob release">
              <svg className="knob-input__visual" viewBox="0 0 40 40">
                <circle
                  className="focus-indicator"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#4eccff"
                  filter="url(#glow)"
                ></circle>
                <circle
                  className="indicator-ring-bg"
                  cx="20"
                  cy="20"
                  r="18"
                  fill="#353b3f"
                  stroke="#23292d"
                ></circle>
                <path
                  className="indicator-ring"
                  d="M20,20Z"
                  fill="#4eccff"
                ></path>
                <g className="dial">
                  <circle
                    cx="20"
                    cy="20"
                    r="16"
                    fill="url(#grad-dial-soft-shadow)"
                  ></circle>
                  <ellipse
                    cx="20"
                    cy="22"
                    rx="14"
                    ry="14.5"
                    fill="#242a2e"
                    opacity="0.15"
                  ></ellipse>
                  <circle
                    cx="20"
                    cy="20"
                    r="14"
                    fill="url(#grad-dial-base)"
                    stroke="#242a2e"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    cx="20"
                    cy="20"
                    r="13"
                    fill="transparent"
                    stroke="url(#grad-dial-highlight)"
                    strokeWidth="1.5"
                  ></circle>
                  <circle
                    className="dial-highlight"
                    cx="20"
                    cy="20"
                    r="14"
                    fill="#fff"
                  ></circle>
                  <circle
                    className="indicator-dot"
                    cx="20"
                    cy="30"
                    r="1.5"
                    fill="#4eccff"
                  ></circle>
                </g>
              </svg>
            </div>
            <div className="fl-studio-envelope__label">rel</div>
          </div>
        </div>
        <div className="fl-studio-envelope__tension">
          <div className="fl-studio-envelope__label"> </div>
          <div className="knob-input fl-studio-envelope__knob tension-knob attack">
            <svg className="knob-input__visual" viewBox="0 0 40 40">
              <circle
                className="focus-indicator"
                cx="20"
                cy="20"
                r="18"
                fill="#4eccff"
                filter="url(#glow)"
              ></circle>
              <circle
                className="indicator-ring-bg"
                cx="20"
                cy="20"
                r="18"
                fill="#353b3f"
                stroke="#23292d"
              ></circle>
              <path
                className="indicator-ring"
                d="M20,20Z"
                fill="#4eccff"
              ></path>
              <g className="dial">
                <circle
                  cx="20"
                  cy="20"
                  r="16"
                  fill="url(#grad-dial-soft-shadow)"
                ></circle>
                <ellipse
                  cx="20"
                  cy="22"
                  rx="14"
                  ry="14.5"
                  fill="#242a2e"
                  opacity="0.15"
                ></ellipse>
                <circle
                  cx="20"
                  cy="20"
                  r="14"
                  fill="url(#grad-dial-base)"
                  stroke="#242a2e"
                  strokeWidth="1.5"
                ></circle>
                <circle
                  cx="20"
                  cy="20"
                  r="13"
                  fill="transparent"
                  stroke="url(#grad-dial-highlight)"
                  strokeWidth="1.5"
                ></circle>
                <circle
                  className="dial-highlight"
                  cx="20"
                  cy="20"
                  r="14"
                  fill="#fff"
                ></circle>
              </g>
            </svg>
          </div>
          <div className="fl-studio-envelope__label">tension</div>
          <div className="knob-input fl-studio-envelope__knob tension-knob decay">
            <svg className="knob-input__visual" viewBox="0 0 40 40">
              <circle
                className="focus-indicator"
                cx="20"
                cy="20"
                r="18"
                fill="#4eccff"
                filter="url(#glow)"
              ></circle>
              <circle
                className="indicator-ring-bg"
                cx="20"
                cy="20"
                r="18"
                fill="#353b3f"
                stroke="#23292d"
              ></circle>
              <path
                className="indicator-ring"
                d="M20,20Z"
                fill="#4eccff"
              ></path>
              <g className="dial">
                <circle
                  cx="20"
                  cy="20"
                  r="16"
                  fill="url(#grad-dial-soft-shadow)"
                ></circle>
                <ellipse
                  cx="20"
                  cy="22"
                  rx="14"
                  ry="14.5"
                  fill="#242a2e"
                  opacity="0.15"
                ></ellipse>
                <circle
                  cx="20"
                  cy="20"
                  r="14"
                  fill="url(#grad-dial-base)"
                  stroke="#242a2e"
                  strokeWidth="1.5"
                ></circle>
                <circle
                  cx="20"
                  cy="20"
                  r="13"
                  fill="transparent"
                  stroke="url(#grad-dial-highlight)"
                  strokeWidth="1.5"
                ></circle>
                <circle
                  className="dial-highlight"
                  cx="20"
                  cy="20"
                  r="14"
                  fill="#fff"
                ></circle>
              </g>
            </svg>
          </div>
          <div className="fl-studio-envelope__label">tension</div>
          <div className="knob-input fl-studio-envelope__knob tension-knob release">
            <svg className="knob-input__visual" viewBox="0 0 40 40">
              <circle
                className="focus-indicator"
                cx="20"
                cy="20"
                r="18"
                fill="#4eccff"
                filter="url(#glow)"
              ></circle>
              <circle
                className="indicator-ring-bg"
                cx="20"
                cy="20"
                r="18"
                fill="#353b3f"
                stroke="#23292d"
              ></circle>
              <path
                className="indicator-ring"
                d="M20,20Z"
                fill="#4eccff"
              ></path>
              <g className="dial">
                <circle
                  cx="20"
                  cy="20"
                  r="16"
                  fill="url(#grad-dial-soft-shadow)"
                ></circle>
                <ellipse
                  cx="20"
                  cy="22"
                  rx="14"
                  ry="14.5"
                  fill="#242a2e"
                  opacity="0.15"
                ></ellipse>
                <circle
                  cx="20"
                  cy="20"
                  r="14"
                  fill="url(#grad-dial-base)"
                  stroke="#242a2e"
                  strokeWidth="1.5"
                ></circle>
                <circle
                  cx="20"
                  cy="20"
                  r="13"
                  fill="transparent"
                  stroke="url(#grad-dial-highlight)"
                  strokeWidth="1.5"
                ></circle>
                <circle
                  className="dial-highlight"
                  cx="20"
                  cy="20"
                  r="14"
                  fill="#fff"
                ></circle>
              </g>
            </svg>
          </div>
        </div>
      </div>
    </>
  );
}
