@startuml ProjectSettings

title Project Settings

database ProjectSettings
entity Arranger
entity Transport

note over ProjectSettings, Transport: User changes quantization
Transport->ProjectSettings: setQ("16n")

note over ProjectSettings,Arranger: Arranger is notified & updates UI
ProjectSettings->Arranger: next({q: "16n"})
Arranger->Arranger: render()

@enduml