@startuml ProjectContext

title Project Settings

database ProjectContext
entity Arranger
entity Transport

note over ProjectContext, Transport: User changes quantization
Transport->ProjectContext: setQ("16n")

note over ProjectContext,Arranger: Arranger is notified & updates UI
ProjectContext->Arranger: next({q: "16n"})
Arranger->Arranger: render()

@enduml